apiVersion: v1
kind: Service
metadata:
  name: cluster-svc
  labels:
    env: demo
spec:
  type: ClusterIP
  ports:
  - port: 80        # Pod port
    targetPort: 80  # Port inside Pod
  selector:
    env: demo
    type: frontend
    