apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    env: demo
spec:
  type: NodePort
  ports:
  - port: 80        # Pod port
    targetPort: 80  # Port inside Pod
    nodePort: 30001 # Port on Node(s) exposed externally
  selector:
    env: demo
    type: frontend
    